import {
  funding,
  advertising,
  consulting,
  partnerships,
  presentation,
  promise,
  twitter,
  facebook,
  instagram,
  ridwan,
} from "../assets";
export const BANNERS = [
  {
    title: "Advertising",
    text: "Increase your business awareness. Ensure your content reaches the greatest number of targeted people possible. Get more conversions and engagements with our discounted advertising plans readily available to you.",
    bgColor: "#E5E3FF",
    icon: advertising,
  },
  {
    title: "Funding Opportunity",
    text: "Every business needs a support system to thrive. Funding support even makes it much easier. With our club partners and merchants, you have ease of access to all the funding information you need for your business.",
    bgColor: "#DBFFDB",
    icon: funding,
  },
  {
    title: "Discounted Consulting Service",
    text: "Tell us how easy doing business would be if you had the right information at the right time at your disposal. Better yet, the right consult. We are your plug for getting access to premium consultation without hassle.",
    bgColor: "#DCFFFF",
    icon: consulting,
  },
  {
    title: "Business Partnerships",
    text: `Increase your business opportunities through strategic collaborations. Although forming business alliances and strategic partnerships takes time and effort to foster. Join our ecosystem of partners to tap into each others' value and deliver solutions to your company and customers.`,
    bgColor: "#FFF1F1",
    icon: partnerships,
  },
  {
    title: "Power Training and Seminars",
    text: "Become a real guru in your industry with the right and relevant education from the Club activities. Our trainings are purposed to help you master the skills essential for commercial growth.",
    bgColor: "#E8FFFF",
    icon: presentation,
  },
];
// title, price, duration, bgColor, features: FEATURES
export const PACKAGES = [
  {
    title: "Basic Access",
    price: "#15,000",
    duration: "03 Months",
    bgColor: "#FD8204",
    features: [
      "Access to database of CC members for 3 months",
      "Discount on services and products from members",
      "Attend one quarterly Business mixer event for FREE",
      "30% off advertising services on Connect Nigeria",
      "Free featured listing for 1 month",
      "One free featured article for the brand",
      "30% discount to attend the mixer for invitees",
      "One social media feature on the brand quarterly",
    ],
  },
  {
    title: "Yanga Access",
    price: "#30,000",
    duration: "06 Months",
    bgColor: "#93D50A",
    features: [
      "Access to database of CC members for 12 months",
      "Discount on services and products from members",
      "Attend 4 Business Mixer events for FREE",
      "One free dedicated newsletter blast",
      "30% off advertising services on Connect Nigeria",
      "Free featured listing for 3 months",
      "One free featured article for the brand",
      "One social media feature on the brand quarterly",
      "30% discount to attend the mixer for other invitees",
      "Meet the boss session for CEO",
    ],
  },
  {
    title: "Corporate Access",
    price: "#60,000",
    duration: "12 Months",
    bgColor: "#0A12D5",
    features: [
      "Attend the quarterly Business mixer events with up to two invitees for free",
      "30% discount to attend the mixer for your other invitees",
      "Get discounts from other members for the validity of your package",
      "Access to database of CC members for package duration",
      "Multiple user access for CEO and 2 staff",
      "Free mentoring/ Learning session Yearly",
      "30% off advertising services on CN",
      "Free featured listing for 3 months",
      "One free featured article for the brand",
      "One free Dedicated newsletter blast for the brand Quarterly",
      "One social media feature on the brand quarterly",
      "30% discount to attend the mixer for other invitees",
      "Free AD days on CN Platform",
      "Meet the boss session for CEO",
    ],
  },
];

export const TESTIMONIALS = [
  {
    name: "Olaniran Ridwan",
    username: "@rydd_1ne",
    text: `Absolutely amazing! This product exceeded my expectations. I can't imagine my life without it now`,
    avatar: ridwan,
    social: twitter,
  },
  {
    name: "Promise Olaifa",
    username: "@omoniyiux",
    text: `Absolutely amazing! This product exceeded my expectations. I can't imagine my life without it now`,
    avatar: promise,
    social: facebook,
  },
  {
    name: "Olaniran Ridwan",
    username: "@ryyd_1ne",
    text: `Absolutely amazing! This product exceeded my expectations. I can't imagine my life without it now`,
    avatar: ridwan,
    social: instagram,
  },
  {
    name: "Promise Olaifa",
    username: "@omoniyiux",
    text: `Absolutely amazing! This product exceeded my expectations. I can't imagine my life without it now`,
    avatar: promise,
    social: facebook,
  },
  {
    name: "Olaniran Ridwan",
    username: "@rydd_1ne",
    text: `Absolutely amazing! This product exceeded my expectations. I can't imagine my life without it now`,
    avatar: ridwan,
    social: instagram,
  },
  {
    name: "Promise Olaifa",
    username: "@omoniyiux",
    text: `Absolutely amazing! This product exceeded my expectations. I can't imagine my life without it now`,
    avatar: promise,
    social: twitter,
  },
];
