export { default as connectLogo } from "./Images/connect-logo.png";
export { default as groupwork } from "./Images/group-working.png";
export { default as personOne } from "./Images/Ellipse 5.png";
export { default as personTwo } from "./Images/Ellipse 6.png";
export { default as personThree } from "./Images/Ellipse 7.png";
export { default as Live } from "./Images/Live.png";
export { default as Adebola } from "./Images/Adebola.png";
export { default as Akolag } from "./Images/Akolag.png";
export { default as QuickGo } from "./Images/QuickGo.png";
export { default as Royal } from "./Images/Royal.png";
export { default as Waves } from "./Images/Waves.png";
export { default as Manifest } from "./Images/Manifest.png";
export { default as Primes } from "./Images/Prime.png";
export { default as Binca } from "./Images/Binca.png";
export { default as funding } from "./Icons/funding.png";
export { default as partnerships } from "./Icons/partnerships.png";
export { default as consulting } from "./Icons/consulting.png";
export { default as advertising } from "./Icons/advertising.png";
export { default as presentation } from "./Icons/presentation.png";
export { default as checkIcon } from "./Icons/Check-icon.png";
export { default as eventImage } from "./Images/event-image.png";
export { default as rightIcon } from "./Icons/right-icon.png";
export { default as leftIcon } from "./Icons/left-icon.png";
export { default as Indicator } from "./Icons/carousel-indicator.png";
export { default as facebook } from "./Icons/facebook.png";
export { default as instagram } from "./Icons/instagram.png";
export { default as twitter } from "./Icons/twitter.png";
export { default as promise } from "./Icons/promise.png";
export { default as ridwan } from "./Icons/ridwan-selfie.png";
export { default as plusIcon } from "./Icons/plus-circle.png";
export { default as minusIcon } from "./Icons/minus-circle.png";
